name: Naim Bridge
version: "1.2.0"
slug: naim_bridge
description: Bridge TCP pour Naim UnitiQute 2
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8765/tcp: 8765
options:
  qute_ip: "192.168.1.108"
  volume_cinema: 45
  volume_spotify: 30
  spotify_client_id: ""
  spotify_client_secret: ""
  spotify_device_name: "Qute"
schema:
  qute_ip: str
  volume_cinema: int
  volume_spotify: int
  spotify_client_id: str
  spotify_client_secret: str
  spotify_device_name: str
